import React from 'react';
import { useTranslation } from 'react-i18next';

const FAQ = () => {
  const { t } = useTranslation();

  return (
    <div className="mt-24 bg-gray-100 dark:bg-zinc-800 text-gray-900 dark:text-white py-12">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold text-center text-blue-500 dark:text-blue-400 mb-8">
          {t('Frequently Asked Questions')}
        </h1>

        <div className="space-y-6">
          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('What is Bagelcademy?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('Bagelcademy is a subscription-based platform offering access to more than 5000 courses. All content, including media and courses, is generated by AI.')}
            </p>
          </div>

          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('What does my subscription include?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('Your subscription gives you unlimited access to over 5000 courses created by AI across various topics.')}
            </p>
          </div>

          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('Can I get a refund?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('No, Bagelcademy does not offer refunds. Please review our terms and conditions before subscribing.')}
            </p>
          </div>

          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('Who owns the courses created by AI?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('All AI-created courses are visible to all users and do not display author information. They are a collaborative effort by Bagelcademy’s AI systems.')}
            </p>
          </div>

          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('How can I contact Bagelcademy for support?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('You can reach us via email at info@bagelcademy.com or call us at 02433052676.')}
            </p>
          </div>

          <div className="bg-white dark:bg-gray-700 rounded-lg p-6 shadow-lg">
            <h2 className="text-2xl font-semibold text-blue-500 dark:text-blue-300">
              {t('How can I stay updated with Bagelcademy\'s latest offerings?')}
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mt-2">
              {t('Follow us on social media or subscribe to our newsletter to get the latest updates and announcements.')}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
